
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
#    exchange:
#        name: demo_register_exchange
#    queue:
#        name: demo_register_queue
#    key: demo_register_key

    listener:
      simple:
        concurrency: 1
        max-concurrency: 5
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
    template:
      mandatory: true
    publisher-confirm-type: correlated
    publisher-returns: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/demo?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 20
logging:
  level:
    org.hibernate.SQL: off